---
title: "MeanDifferences"
output: html_document
date: '2023-04-18'
---

Read in the data
```{r}
library(tidyverse)
library(ggplot2)
library(effsize)
library(dplyr)

data <- read.csv("satisfaction_2015.csv", header = TRUE)
summary(data)
```

Business travelers means by classes
```{r}
dataBT <- data %>%  
  filter(Type.of.Travel == 'Business travel' & Class != 'Eco Plus')

dataBT[dataBT == 0] <- NA
view(dataBT)


#Class as factor + levels 
dataBT$Class <- factor(dataBT$Class)

library(dplyr)

dataBT %>%
  group_by(Class) %>% 
  summarise(across(c("Inflight.wifi.service", "Departure.Arrival.time.convenient", "Ease.of.Online.booking", "Gate.location", "Food.and.drink", "Online.boarding", "Seat.comfort", "Inflight.entertainment", "On.board.service", "Leg.room.service", "Baggage.handling", "Checkin.service", "Inflight.service", "Cleanliness"), ~mean(., na.rm = TRUE)))
```

Personal travelers means by classes
```{r}
dataPT <- data %>%  
  filter(Type.of.Travel == 'Personal Travel' & Class != 'Eco Plus')

dataPT[dataPT == 0] <- NA
view(dataPT)

#Class as factor + levels 
dataPT$Class <- factor(dataPT$Class)

dataPT %>%
  group_by(Class) %>% 
  summarise(across(c("Inflight.wifi.service", "Departure.Arrival.time.convenient", "Ease.of.Online.booking", "Gate.location", "Food.and.drink", "Online.boarding", "Seat.comfort", "Inflight.entertainment", "On.board.service", "Leg.room.service", "Baggage.handling", "Checkin.service", "Inflight.service", "Cleanliness"), ~mean(., na.rm = TRUE)))
```

Business class travelers means by type of travel
```{r}
dataBC <- data %>%  
  filter(Class == 'Business')

dataBC[dataBC == 0] <- NA
view(dataBC)

#Class as factor + levels 
dataBC$Class <- factor(dataBC$Class)

dataBC %>%
  group_by(Type.of.Travel) %>% 
  summarise(across(c("Inflight.wifi.service", "Departure.Arrival.time.convenient", "Ease.of.Online.booking", "Gate.location", "Food.and.drink", "Online.boarding", "Seat.comfort", "Inflight.entertainment", "On.board.service", "Leg.room.service", "Baggage.handling", "Checkin.service", "Inflight.service", "Cleanliness"), ~mean(., na.rm = TRUE)))

dataBC %>%
  pivot_longer(cols = c("Inflight.wifi.service", "Departure.Arrival.time.convenient", "Ease.of.Online.booking", "Gate.location", "Food.and.drink", "Online.boarding", "Seat.comfort", "Inflight.entertainment", "On.board.service", "Leg.room.service", "Baggage.handling", "Checkin.service", "Inflight.service", "Cleanliness")) %>%
  group_by(Type.of.Travel, name) %>%
  summarise(mean_score = mean(value, na.rm = TRUE)) %>%
  ggplot(aes(x = Type.of.Travel, y = mean_score, fill = name)) +
  geom_col(position = "dodge") +
  labs(x = "Type of Travel", y = "Mean Score", fill = "Variable")
```

Economy class travelers means by type of travel
```{r}
dataEC <- data %>%  
  filter(Class == 'Eco')

dataEC[dataEC == 0] <- NA
view(dataEC)

#Class as factor + levels 
dataEC$Class <- factor(dataEC$Class)

dataEC %>%
  group_by(Type.of.Travel) %>% 
  summarise(across(c("Inflight.wifi.service", "Departure.Arrival.time.convenient", "Ease.of.Online.booking", "Gate.location", "Food.and.drink", "Online.boarding", "Seat.comfort", "Inflight.entertainment", "On.board.service", "Leg.room.service", "Baggage.handling", "Checkin.service", "Inflight.service", "Cleanliness"), ~mean(., na.rm = TRUE)))

dataEC %>%
  pivot_longer(cols = c("Inflight.wifi.service", "Departure.Arrival.time.convenient", "Ease.of.Online.booking", "Gate.location", "Food.and.drink", "Online.boarding", "Seat.comfort", "Inflight.entertainment", "On.board.service", "Leg.room.service", "Baggage.handling", "Checkin.service", "Inflight.service", "Cleanliness")) %>%
  group_by(Type.of.Travel, name) %>%
  summarise(mean_score = mean(value, na.rm = TRUE)) %>%
  ggplot(aes(x = Type.of.Travel, y = mean_score, fill = name)) +
  geom_col(position = "dodge") +
  labs(x = "Type of Travel", y = "Mean Score", fill = "Variable")
```

```{r}
data_clean <- data %>%  
  select(-c (id,Customer.Type,satisfaction_v2,Departure.Delay.in.Minutes,Arrival.Delay.in.Minutes))  
  
#Class as factor + levels 
data_clean$Class <- factor(data_clean$Class)

class_levels <- levels(data_clean$Class)

data_clean <- data_clean %>%
  mutate_at(vars(Seat.comfort, Online.boarding, On.board.service, Baggage.handling, Checkin.service, Inflight.service, Inflight.wifi.service, Departure.Arrival.time.convenient, Ease.of.Online.booking, Gate.location, Food.and.drink, Inflight.entertainment, Leg.room.service, Cleanliness), as.numeric)

data_clean <- data_clean %>% 
  filter(!is.na(Seat.comfort)) %>% 
  filter(!is.na(Online.boarding))  %>% 
  filter(!is.na(On.board.service)) %>% 
  filter(!is.na(Baggage.handling))  %>% 
  filter(!is.na(Checkin.service)) %>% 
  filter(!is.na(Inflight.service))  %>% 
  filter(!is.na(Inflight.wifi.service)) %>% 
  filter(!is.na(Departure.Arrival.time.convenient))  %>% 
  filter(!is.na(Ease.of.Online.booking))  %>% 
  filter(!is.na(Gate.location)) %>% 
  filter(!is.na(Food.and.drink))  %>% 
  filter(!is.na(Inflight.entertainment)) %>% 
  filter(!is.na(Cleanliness))  %>% 
  filter(!is.na(Leg.room.service)) 

#Mean business travelers in business class
meanBBC <- data_clean %>%
  filter(Type.of.Travel == 'Business travel' & Class == "Business" & Class != 'Eco Plus' ) %>%
  select(Seat.comfort, Online.boarding, On.board.service, Baggage.handling, Checkin.service, Inflight.service, Inflight.wifi.service, Departure.Arrival.time.convenient, Ease.of.Online.booking, Gate.location, Food.and.drink, Inflight.entertainment, Leg.room.service, Cleanliness) %>%
  unlist() %>%
  mean()

#Mean business travelers in economy class
meanBEC <- data_clean %>%
  filter(Type.of.Travel == 'Business travel' & Class == "Eco" & Class != 'Eco Plus' ) %>%
  select(Seat.comfort, Online.boarding, On.board.service, Baggage.handling, Checkin.service, Inflight.service, Inflight.wifi.service, Departure.Arrival.time.convenient, Ease.of.Online.booking, Gate.location, Food.and.drink, Inflight.entertainment, Leg.room.service, Cleanliness) %>%
  unlist() %>%
  mean()

#Mean personal travelers in business class
meanPBC <- data_clean %>%
  filter(Type.of.Travel == 'Personal Travel' & Class == "Business" & Class != 'Eco Plus' ) %>%
  select(Seat.comfort, Online.boarding, On.board.service, Baggage.handling, Checkin.service, Inflight.service, Inflight.wifi.service, Departure.Arrival.time.convenient, Ease.of.Online.booking, Gate.location, Food.and.drink, Inflight.entertainment, Leg.room.service, Cleanliness) %>%
  unlist() %>%
  mean()

#Mean personal travelers in economy class
meanPEC <- data_clean %>%
  filter(Type.of.Travel == 'Personal Travel' & Class == "Eco" & Class != 'Eco Plus' ) %>%
  select(Seat.comfort, Online.boarding, On.board.service, Baggage.handling, Checkin.service, Inflight.service, Inflight.wifi.service, Departure.Arrival.time.convenient, Ease.of.Online.booking, Gate.location, Food.and.drink, Inflight.entertainment, Leg.room.service, Cleanliness) %>%
  unlist() %>%
  mean()

#Graphic
means_df <- data.frame(Type.of.Travel = c("Business Travel", "Business Travel", "Personal Travel", "Personal Travel"),
                        Class = c("Business", "Eco", "Business", "Eco"),
                        Mean = c(meanBBC, meanBEC, meanPBC, meanPEC))

ggplot(means_df, aes(x = Type.of.Travel, y = Mean, fill = Class)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Type of Travel", y = "Satisfaction Level") +
  ggtitle("Mean Satisfaction Level by Type of Travel and Class") +
  scale_fill_manual(values = c("Business" = "blue", "Eco" = "red")) +
  ylim(0, 5)
```